

execute:1622, Driver (org.apache.hadoop.hive.ql)
runInternal:1503, Driver (org.apache.hadoop.hive.ql)
run:1287, Driver (org.apache.hadoop.hive.ql)
run:1277, Driver (org.apache.hadoop.hive.ql)
processLocalCmd:226, CliDriver (org.apache.hadoop.hive.cli)
processCmd:175, CliDriver (org.apache.hadoop.hive.cli)
processLine:389, CliDriver (org.apache.hadoop.hive.cli)
executeDriver:781, CliDriver (org.apache.hadoop.hive.cli)
run:699, CliDriver (org.apache.hadoop.hive.cli)
main:634, CliDriver (org.apache.hadoop.hive.cli)
invoke0:-1, NativeMethodAccessorImpl (sun.reflect)
invoke:62, NativeMethodAccessorImpl (sun.reflect)
invoke:43, DelegatingMethodAccessorImpl (sun.reflect)
invoke:497, Method (java.lang.reflect)
run:226, RunJar (org.apache.hadoop.util)
main:141, RunJar (org.apache.hadoop.util)


// 
executeTask:214, Task (org.apache.hadoop.hive.ql.exec)
runSequential:99, TaskRunner (org.apache.hadoop.hive.ql.exec)
launchTask:2054, Driver (org.apache.hadoop.hive.ql)
execute:1750, Driver (org.apache.hadoop.hive.ql)
runInternal:1503, Driver (org.apache.hadoop.hive.ql)
run:1287, Driver (org.apache.hadoop.hive.ql)
run:1277, Driver (org.apache.hadoop.hive.ql)
processLocalCmd:226, CliDriver (org.apache.hadoop.hive.cli)
processCmd:175, CliDriver (org.apache.hadoop.hive.cli)
processLine:389, CliDriver (org.apache.hadoop.hive.cli)
executeDriver:781, CliDriver (org.apache.hadoop.hive.cli)
run:699, CliDriver (org.apache.hadoop.hive.cli)
main:634, CliDriver (org.apache.hadoop.hive.cli)
invoke0:-1, NativeMethodAccessorImpl (sun.reflect)
invoke:62, NativeMethodAccessorImpl (sun.reflect)
invoke:43, DelegatingMethodAccessorImpl (sun.reflect)
invoke:497, Method (java.lang.reflect)
run:226, RunJar (org.apache.hadoop.util)
main:141, RunJar (org.apache.hadoop.util)

